name: Investigate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 25 * *'

jobs:
  investigate:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            const script = require('./ci-services.js');
            const result = await script({github});
            const aggregation = {
              CircleCI: result.filter(x => x.CircleCI).length,
              TravisCI: result.filter(x => x.TravisCI).length,
              Drone: result.filter(x => x.Drone).length,
              AzurePipelines: result.filter(x => x.AzurePipelines).length,
              Appveyor: result.filter(x => x.Appveyor).length,
              GitLabCICD: result.filter(x => x.GitLabCICD).length,
              GitHubActions: result.filter(x => x.GitHubActions).length,
              None: result.filter(x => !x.CircleCI && !x.TravisCI && !x.Drone && !x.AzurePipelines && !x.Appveyor && !x.GitHubActions).length,
            };
            console.log('CircleCI', result.filter(x => x.CircleCI).length);
            console.log('Travis CI', result.filter(x => x.TravisCI).length);
            console.log('Drone', result.filter(x => x.Drone).length);
            console.log('Azure Pipelines', result.filter(x => x.AzurePipelines).length);
            console.log('Appveyor', result.filter(x => x.Appveyor).length);
            console.log('GitLab CI/CD', result.filter(x => x.GitLabCICD).length);
            console.log('GitHub Actions', result.filter(x => x.GitHubActions).length);
            console.log('None', result.filter(x => !x.CircleCI && !x.TravisCI && !x.Drone && !x.AzurePipelines && !x.Appveyor && !x.GitHubActions).length);
            console.log('----------');
            console.log('Total', result.length);
            console.log('==========');
            console.log(result);
            await fs.writeFile('./ci-services.json', JSON.stringify(result, null, 2));
            await fs.writeFile('./aggregation.json', JSON.stringify(aggregation, null, 2));
      - uses: snow-actions/git-config-user@v1.0.0
      - id: diff
        run: |
          git add -N .
          git diff --exit-code
        continue-on-error: true
      - run: |
          git add .
          git commit -m 'Update'
          git push
        if: steps.diff.outcome == 'failure'
